### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bbkr** [MARTIMM/BSON#1]
Current BSON implementation is pushed as far as Perl6 Rakudo allows.

* once we get pack/unpack in Rakudo we can implement 8 bytes (64-bit IEEE 754 floating point) and push such MongoDB features like authentication

**Comment by MARTIMM** [comment]
While waiting for pack/unpack there are emulations to implement 64-bit IEEE 754 floating point numbers from the Num typed variables.
