### ISSUE TITLE
Documentation outdated - BSON.new is not possible on package.

### ISSUE THREAD

**Issue by bbkr** [MARTIMM/BSON#11]
Hi

```perl
perl6 -e 'use BSON; BSON.new;'
You cannot create an instance of this type
  in block <unit> at -e:1
```

Previously BSON was Role and it could be used as standalone object instance.
Now it is a package, but documentation still says in SYNOPSIS that ```BSON.new``` is valid usage.

**Comment by MARTIMM** [comment]
Thanks for mentioning, Sorry for the late response

Changed the readme. Can do now;
```perl6 -e 'use BSON; BSON::Bson.new;'```
