### ISSUE TITLE
Deprecated Code: is_approx

### ISSUE THREAD

**Issue by zoffixznet** [MARTIMM/BSON#15]
Hi, your repository [contains instances of old `is_approx` testing function](https://github.com/MARTIMM/BSON/blob/master/Tests/701-decoder.t#L41). That function has been deprecated for several months and will be **removed** entirely from Rakudo in December (tentatively, Dec. 17).

Please upgrade to the [new `is-approx`](https://docs.perl6.org/language/testing#index-entry-is-approx-is-approx%28%24value%2C_%24expected%2C_%24description%3F%29). If you did not specify custom tolerance argument, simply renaming from `is_approx` to `is-approx` is sufficient.

**Comment by MARTIMM** [comment]
checkecd long time ago but forgot to close the issue
