### ISSUE TITLE
threadpool exhaustion

### ISSUE THREAD

**Issue by MARTIMM** [MARTIMM/BSON#20]
Need to be more careful when using threads for encoding and decoding documents. In some project of mine, the process runs into a lock waiting for a promise to finish. An answer from [Jnthn at SO](https://stackoverflow.com/questions/43449883/how-many-promises-can-perl-6-keep). The quick fix mentioned didn't help (yet).

**Comment by bbkr** [comment]
Basically you should not use promises in "BFS" style when handling nested structure in "DFS" style.

My proposal for fix would be to drop %!promises hash entirely and handle promises also in DFS style.
From each level you should return composite allof promise that won't ever lock threadpool, no matter how many threads are available.

http://blogs.perl.org/users/pawel_bbkr_pabian/2015/09/asynchronous-parallel-and-dead-my-perl-6-daily-bread.html - I've struggled with this topic not so long ago, so code snippets should be up to date.

This will also allow basically to remove Promises from specific types and leave them only on hash/array level.

**Comment by MARTIMM** [comment]
Thanks for the tip, I'll look into it.

**Comment by MARTIMM** [comment]
I'll finish this later, there is some irregular on and off time coming and would not like to leave a commit which makes the whole unworkable.

**Comment by MARTIMM** [comment]
Implemented and tested also in MongoDB
