### ISSUE TITLE
Dates created by '$currentDate' are parsed incorrectly

### ISSUE THREAD

**Issue by lefth** [MARTIMM/BSON#25]
To see the problem, run the following script. If the server is running on localhost, a date created by `DateTime.new(now)` should be almost the same as a time created by the MongoDB `$currentDate` operator. This script prints the difference. The desired result should be less than 1 second. The actual result is thousands of years.

    #! env perl6
    
    use BSON::Document;
    use MongoDB::Client;
    
    my MongoDB::Client $client .= new(:uri("mongodb://127.0.0.1"));
    my $db = $client.database('test');
    
    my DateTime $startTime;
    
    sub record-time() {
    	$startTime = DateTime.new(now);
    	my BSON::Document $req .= new: (
    		update => 'timetest',
    		updates => [ (
    			q => (name => 'time-test',),
    			u => ('$currentDate' => (lastModified => True),),
    			upsert => True,
    		  ),
    		],
    	);
    	my $response = $db.run-command($req);
    	say $response;
    }
    
    sub check-time {
    	my $response = $db.collection('timetest').find(
    		:number-to-return(1),
    		:criteria(name => 'time-test', lastModified => ('$exists' => True),),
    	).fetch;
    
    	say 'Time between request and DB action: '~($response<lastModified>-$startTime);
    }
    
    record-time;
    check-time;

**Comment by MARTIMM** [comment]
PR is merged, Thanks Dan
