### ISSUE TITLE
Documents should support destructuring

### ISSUE THREAD

**Issue by lefth** [MARTIMM/BSON#27]
In function signatures, sub-elements of objects can be mapped to variables:

    sub print-id(% (:_id($id))) { say $id; }
    print-id $(_id => 4);
    # output: 4
    my %doc := BSON::Document.new: (_id => 4,)
    print-id %doc;
    # output: (Any)

As you can see, this fails. Since documents are used like Hash, they should implement this feature as well. I'll make a pull request that implements this shortly.

**Comment by MARTIMM** [comment]
I understand this now. It is a nice addition, thanks
