### ISSUE TITLE
Parallelize processing

### ISSUE THREAD

**Issue by bbkr** [MARTIMM/BSON#3]
Whole parallelization can be implemented in `e_list` type (hashes are also treated as arrays).

```perl
multi method _e_list ( @p ) {
    
    return Buf.new unless @p;
    return [~]( @p>>.map: { self._element( $_ ) } );
}
```

So far in Rakudo:
* hyperoperator dispatch is in place but no true parallel processing happens, that gives about 10% performance drop compared to [serial processing](https://github.com/bbkr/BSON/blob/0d8721d60ca54cc36e3e4e2cd14e2e4798d7542e/lib/BSON.pm#L49-58)
* [~ reduce bug for Buf](https://rt.perl.org/rt3/Ticket/Display.html?id=117589) occurs

Once those issues are resolved parallelization can be implemented.

**Comment by bbkr** [comment]
Buf bug is fixed.

I'm not sure if hyper >> still works as before because all parallel stuff has now Promises and Supplies.
Simple benchmark should show huge improvement.

**Comment by bbkr** [comment]
I've tried Promise approach.

```
method encode_e_list ( *@p --> Buf ) {
       return Buf.new unless @p;
       return [~](await do for @p { start { self.encode_element( $_ ) } } );
}
```

But it deadlocks. For example when encoding hash with 10 keys holding arrays of 10 elements everything works. But hash with 10 keys holding arrays of 20 elements uses all available threads and outer (encoding hash) or inner (encoding array elements) awaits won't complete because they are all half-way started.

I'm not sure what valid solution should look like.

**Comment by MARTIMM** [comment]
A new module BSON::Document is written to handle issues caused by using Hash. The main problem with hashes is changing the input order of key-value pairs. This is handled in the new module. Because it is written in pure perl it is much slower than using hashes which use also nqp.
The module also parallelize the encode and decode processes.

**Comment by MARTIMM** [comment]
After some time running the BSON::Document module I am rather satisfied with it. Perl6's speed has improved in the mean time and will continue to do so. Later I will decide if there can be any code improvements
