### ISSUE TITLE
Switch to native int/num decode methods.

### ISSUE THREAD

**Issue by bbkr** [MARTIMM/BSON#31]
Rakudo now has built-in methods that duplicate custom decodings in BSON code:
https://docs.perl6.org/type/Blob#Methods_on_blob8_only_(6.d,_2018.12_and_later)

They are really fast, so maybe it's worth switching to those methods?
Current methods can be left as fallback until most Rakudo builds (Star, linux, macOS) are at least 2019.01 (there were some issues with endian flags fixed after 2018.12).

**Comment by MARTIMM** [comment]
I am so sorry that I haven't seen your input. I somehow had unwatched the repo and therefore did not notice.
I'll will look into it

**Comment by MARTIMM** [comment]
Oops, found the 'write' ones too!
