### ISSUE TITLE
Native pack/unpack

### ISSUE THREAD

**Issue by bbkr** [MARTIMM/BSON#4]
Replace https://github.com/bbkr/BSON/blob/0d8721d60ca54cc36e3e4e2cd14e2e4798d7542e/lib/BSON.pm#L247-L256

with native pack/unpack methods. It is possible right now but results in performance drop.

**Comment by bbkr** [comment]
WARNING: pack/unpack was just copied from Perl 5 and was never specced correctly.
And implementation is removed without deprecation.

"This is the other reason for ripping out the pack/unpack implementations, as opposed to spec’ing them as-is for now or something. I don’t want people to end up relying on some unspecified subset of P5’s way of handling binary data, when it could very easily not be how we end up doing this sort of thing. If incidentally P5’s solution is the best way, then that’s fine, I just want to make sure whatever kind of pack/unpack we end up having isn’t in danger of being replaced once people start seriously relying upon it, and thus having to implement some kind of deprecation thing for it. (Since pack/unpack was never spec’d, I personally don’t think we’d need to deprecate the existing functionality, but YMMV.)"


So this issue should wait until pack/unpack are well specced.

**Comment by MARTIMM** [comment]
Not using pack/unpack but depending on the nativeCall mechanisms and other implementation methods. A lot can be encoded and decoded this way.
